apt: pkgAcqFile Class Reference
pkgAcqFile Class Reference
Acquire system {{{
Retrieve an arbitrary file to the current directory. {{{.
#include <acquire-item.h>
Public Member Functions
virtual void Failed (std::string Message, pkgAcquire::MethodConfig *Cnf)
Invoked by the acquire worker when the object couldn't be fetched.
virtual void Done (std::string Message, unsigned long long Size, std::string CalcHash, pkgAcquire::MethodConfig *Cnf)
Invoked by the acquire worker when the object was fetched successfully.
virtual std::string DescURI ()
A "descriptive" URI-like string.
virtual std::string HashSum ()
HashSum.
virtual std::string Custom600Headers ()
Custom headers to be sent to the fetch process.
pkgAcqFile (pkgAcquire *Owner, std::string URI, std::string Hash, unsigned long long Size, std::string Desc, std::string ShortDesc, const std::string &DestDir="", const std::string &DestFilename="", bool IsIndexFile=false)
Create a new pkgAcqFile object.
Detailed Description
Retrieve an arbitrary file to the current directory. {{{.
The file is retrieved even if it is accessed via a URL type that normally is a NOP, such as "file". If the download fails, the partial file is renamed to get a ".FAILED" extension.
Constructor & Destructor Documentation
pkgAcqFile (pkgAcquire * Owner, std::string URI, std::string Hash, unsigned long long Size, std::string Desc, std::string ShortDesc, const std::string & DestDir = "", const std::string & DestFilename = "", bool IsIndexFile = false)
Create a new pkgAcqFile object.
Parameters:
Owner The pkgAcquire object with which this object is associated.
URI The URI to download.
Hash The hashsum of the file to download, if it is known; otherwise "".
Size The size of the file to download, if it is known; otherwise 0.
Desc A description of the file being downloaded.
ShortDesc A brief description of the file being downloaded.
DestDir The directory the file should be downloaded into.
DestFilename The filename+path the file is downloaded to.
IsIndexFile The file is considered a IndexFile and cache-control headers like "cache-control: max-age=0" are send
If DestFilename is empty, download to DestDir/<basename> if DestDir is non-empty, $CWD/<basename> otherwise. If DestFilename is NOT empty, DestDir is ignored and DestFilename is the absolute name to which the file should be downloaded.
References pkgAcquire::ItemDesc::Description, pkgAcquire::Item::DestFile, pkgAcquire::Item::FileSize, pkgAcquire::ItemDesc::Owner, pkgAcquire::Item::PartialSize, pkgAcquire::Item::QueueURI(), pkgAcquire::Item::ShortDesc(), pkgAcquire::ItemDesc::ShortDesc, and pkgAcquire::ItemDesc::URI.
Member Function Documentation
string Custom600Headers () [virtual]
Custom headers to be sent to the fetch process.
Returns:
a string containing RFC822-style headers that are to be inserted into the 600 URI Acquire message sent to the fetch subprocess. The headers are inserted after a newline-less line, so they should (if nonempty) have a leading newline and no trailing newline.
Reimplemented from pkgAcquire::Item.
virtual std::string DescURI () [inline, virtual]
A "descriptive" URI-like string.
Returns:
a URI that should be used to describe what is being fetched.
Implements pkgAcquire::Item.
References pkgAcquire::ItemDesc::URI.
void Done (std::string Message, unsigned long long Size, std::string Hash, pkgAcquire::MethodConfig * Cnf) [virtual]
Invoked by the acquire worker when the object was fetched successfully.
Note that the object might not have been written to DestFile; check for the presence of an Alt-Filename entry in Message to find the file to which it was really written.
Done is often used to switch from one stage of the processing to the next (e.g. fetching, unpacking, copying). It is one branch of the continuation of the fetch process.
Parameters:
Message Data from the acquire method. Use LookupTag() to parse it.
Size The size of the object that was fetched.
Hash The HashSum of the object that was fetched.
Cnf The method via which the object was fetched.
See also:
pkgAcqMethod
Reimplemented from pkgAcquire::Item.
References pkgAcquire::Item::Complete, pkgAcquire::Item::DestFile, pkgAcquire::Item::ErrorText, pkgAcquire::Item::Local, pkgAcquire::Item::QueueURI(), pkgAcquire::MethodConfig::Removable, pkgAcquire::Item::Rename(), pkgAcquire::Item::StatError, and pkgAcquire::ItemDesc::URI.
void Failed (std::string Message, pkgAcquire::MethodConfig * Cnf) [virtual]
Invoked by the acquire worker when the object couldn't be fetched.
This is a branch of the continuation of the fetch process.
Parameters:
Message An RFC822-formatted message from the acquire method describing what went wrong. Use LookupTag() to parse it.
Cnf The method via which the worker tried to fetch this object.
See also:
pkgAcqMethod
Reimplemented from pkgAcquire::Item.
References pkgAcquire::Item::ErrorText, pkgAcquire::MethodConfig::LocalOnly, and pkgAcquire::Item::QueueURI().
virtual std::string HashSum () [inline, virtual]
HashSum.
Returns:
the HashSum of this object, if applicable; otherwise, an empty string.
Reimplemented from pkgAcquire::Item.
The documentation for this class was generated from the following files:
/home/rpmuser/debian/debian_apt/apt-0.8.16~exp12ubuntu10.16/apt-pkg/acquire-item.h
/home/rpmuser/debian/debian_apt/apt-0.8.16~exp12ubuntu10.16/apt-pkg/acquire-item.cc