apt: pkgAcqMetaSig Class Reference
pkgAcqMetaSig Class Reference
Acquire system {{{
An acquire item that downloads the detached signature {{{ of a meta-index (Release) file, then queues up the release file itself.
#include <acquire-item.h>
Public Member Functions
virtual void Failed (std::string Message, pkgAcquire::MethodConfig *Cnf)
Invoked by the acquire worker when the object couldn't be fetched.
virtual void Done (std::string Message, unsigned long long Size, std::string Md5Hash, pkgAcquire::MethodConfig *Cnf)
Invoked by the acquire worker when the object was fetched successfully.
virtual std::string Custom600Headers ()
Custom headers to be sent to the fetch process.
virtual std::string DescURI ()
A "descriptive" URI-like string.
pkgAcqMetaSig (pkgAcquire *Owner, std::string URI, std::string URIDesc, std::string ShortDesc, std::string MetaIndexURI, std::string MetaIndexURIDesc, std::string MetaIndexShortDesc, const std::vector< struct IndexTarget * > *IndexTargets, indexRecords *MetaIndexParser)
Create a new pkgAcqMetaSig.
Protected Attributes
std::string LastGoodSig
The last good signature file.
pkgAcquire::ItemDesc Desc
The fetch request that is currently being processed.
std::string RealURI
The URI of the signature file. Unlike Desc.URI, this is never modified; it is used to determine the file that is being downloaded.
std::string MetaIndexURI
The URI of the meta-index file to be fetched after the signature.
std::string MetaIndexURIDesc
A "URI-style" description of the meta-index file to be fetched after the signature.
std::string MetaIndexShortDesc
A brief description of the meta-index file to be fetched after the signature.
indexRecords * MetaIndexParser
A package-system-specific parser for the meta-index file.
const std::vector< struct
IndexTarget * > * IndexTargets
The index files which should be looked up in the meta-index and then downloaded.
Detailed Description
An acquire item that downloads the detached signature {{{ of a meta-index (Release) file, then queues up the release file itself.
Todo:
Why protected members?
See also:
pkgAcqMetaIndex
Member Function Documentation
string Custom600Headers () [virtual]
Custom headers to be sent to the fetch process.
Returns:
a string containing RFC822-style headers that are to be inserted into the 600 URI Acquire message sent to the fetch subprocess. The headers are inserted after a newline-less line, so they should (if nonempty) have a leading newline and no trailing newline.
Reimplemented from pkgAcquire::Item.
References LastGoodSig.
virtual std::string DescURI () [inline, virtual]
A "descriptive" URI-like string.
Returns:
a URI that should be used to describe what is being fetched.
Implements pkgAcquire::Item.
References RealURI.
void Done (std::string Message, unsigned long long Size, std::string Hash, pkgAcquire::MethodConfig * Cnf) [virtual]
Invoked by the acquire worker when the object was fetched successfully.
Note that the object might not have been written to DestFile; check for the presence of an Alt-Filename entry in Message to find the file to which it was really written.
Done is often used to switch from one stage of the processing to the next (e.g. fetching, unpacking, copying). It is one branch of the continuation of the fetch process.
Parameters:
Message Data from the acquire method. Use LookupTag() to parse it.
Size The size of the object that was fetched.
Hash The HashSum of the object that was fetched.
Cnf The method via which the object was fetched.
See also:
pkgAcqMethod
Reimplemented from pkgAcquire::Item.
References pkgAcquire::Item::Complete, Desc, pkgAcquire::Item::DestFile, pkgAcquire::Item::ErrorText, IndexTargets, LastGoodSig, pkgAcquire::Item::Local, MetaIndexShortDesc, MetaIndexURI, MetaIndexURIDesc, pkgAcquire::Item::QueueURI(), pkgAcquire::Item::Rename(), pkgAcquire::Item::StatError, and pkgAcquire::ItemDesc::URI.
void Failed (std::string Message, pkgAcquire::MethodConfig * Cnf) [virtual]
Invoked by the acquire worker when the object couldn't be fetched.
This is a branch of the continuation of the fetch process.
Parameters:
Message An RFC822-formatted message from the acquire method describing what went wrong. Use LookupTag() to parse it.
Cnf The method via which the worker tried to fetch this object.
See also:
pkgAcqMethod
Reimplemented from pkgAcquire::Item.
References pkgAcquire::Item::Complete, pkgAcquire::Item::Dequeue(), IndexTargets, LastGoodSig, pkgAcquire::MethodConfig::LocalOnly, MetaIndexShortDesc, MetaIndexURI, MetaIndexURIDesc, RealURI, pkgAcquire::Item::Rename(), pkgAcquire::Item::StatDone, and pkgAcquire::Item::StatTransientNetworkError.
Member Data Documentation
const std::vector<struct IndexTarget*>* IndexTargets [protected]
The index files which should be looked up in the meta-index and then downloaded.
Todo:
Why a list of pointers instead of a list of structs?
Referenced by Done(), and Failed().
The documentation for this class was generated from the following files:
/home/rpmuser/debian/debian_apt/apt-0.8.16~exp12ubuntu10.16/apt-pkg/acquire-item.h
/home/rpmuser/debian/debian_apt/apt-0.8.16~exp12ubuntu10.16/apt-pkg/acquire-item.cc