'\" t
.\"     Title: apt-extracttemplates
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 29
Fevereiro 2004
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-EXTRACTTEMPLATE" "1" "29 Fevereiro 2004" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-extracttemplates \- Utilitário para extrair configurações e modelos DebConf a partir de pacotes Debian
.SH "SYNOPSIS"
.HP \w'\fBapt\-extracttemplates\fR\ 'u
\fBapt\-extracttemplates\fR [\fB\-hv\fR] [\fB\-t=\fR\fB\fIdirectório\ temporário\fR\fR] \fIficheiro\fR...
.SH "DESCRIçãO"
.PP
\fBapt\-extracttemplates\fR
irá receber um ou mais ficheiros de pacotes Debian na sua entrada e escrever (para um directório temporário) todos os scripts de configuração associados e ficheiros de modelo\&. Por cada pacote passado por ele que contenha scripts de configuração e modelos, será gerada uma linha no formato:
.PP
pacote versão ficheiro\-modelo script\-de\-configuração
.PP
ficheiro\-modelo e script\-de\-configuração são escritos num directório temporário especificado por \-t ou \-\-tempdir (APT::ExtractTemplates::TempDir) directório, com nomes de ficheiros no formato
pacote\&.modelo\&.XXXX
e
pacote\&.configuração\&.XXXX
.SH "OPçõES"
.PP
Todas as opções de linha de comandos podem ser definidas usando o ficheiro de configuração, as descrições indicam a opção de configuração a definir\&. Para opções booleanas você pode sobre por o ficheiro de configuração usando algo como
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou várias outras variantes\&.
.PP
\fB\-t\fR, \fB\-\-tempdir\fR
.RS 4
Directório temporário para onde escrever ficheiros debconf modelo extraídos e scripts de configuração\&. Item de Configuração:
APT::ExtractTemplates::TempDir
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra um sumário curto da utilização\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Mostra a versão do programa\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Ficheiro de Configuração; Especifica o ficheiro de configuração a usar\&. O programa irá ler o ficheiro de configuração predefinido e depois este ficheiro de configuração\&. Se as definições de configuração precisarem de ser definidas antes, os ficheiros de configuração predefinidos são analisados especificando um ficheiro com a variável de ambiente
\fBAPT_CONFIG\fR\&. Veja
\fBapt.conf\fR(5)
para informação de sintaxe\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Define uma Opção de Configuração; Isto irá definir uma opção de configuração arbitrária\&. A sintaxe é
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
e
\fB\-\-option\fR
podem ser usadas várias vezes para definir opções diferentes\&.
.RE
.SH "VEJA TAMBéM"
.PP
\fBapt.conf\fR(5)
.SH "DIAGNóSTICO"
.PP
\fBapt\-extracttemplates\fR
devolve zero na operação normal, 100 decimal em erro\&.
.SH "BUGS"
.PP
\m[blue]\fBpágina de bugs do APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Se deseja reportar um bug no APT, por favor veja
/usr/share/doc/debian/bug\-reporting\&.txt
ou o comando
\fBreportbug\fR(1)\&.
.SH "TRADUÇÃO"
.PP
A tradução Portuguesa foi feita por Américo Monteiro
<a_monteiro@netcabo\&.pt>
em 2009, 2010\&. A tradução foi revista pela equipa de traduções portuguesas da Debian
<traduz@debianpt\&.org>\&.
.PP
Note que este documento traduzido pode conter partes não traduzidas\&. Isto é feito propositadamente, para evitar perdas de conteúdo quando a tradução está atrasada relativamente ao conteúdo original\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT team\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
página de bugs do APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
