'\" t
.\"     Title: apt-cdrom
.\"    Author: Jason Gunthorpe
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 14
Fevereiro 2004
.\"    Manual: APT
.\"    Source: Linux
.\"  Language: English
.\"
.TH "APT\-CDROM" "8" "14 Fevereiro 2004" "Linux" "APT"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
apt-cdrom \- Utilitário de gestão de CDROM do APT
.SH "SYNOPSIS"
.HP \w'\fBapt\-cdrom\fR\ 'u
\fBapt\-cdrom\fR [\fB\-hvrmfan\fR] [\fB\-d=\fR\fB\fIponto\ de\ montagem\ do\ cdrom\fR\fR] [\fB\-o=\fR\fB\fIstring\ de\ configuração\fR\fR] [\fB\-c=\fR\fB\fIficheiro\fR\fR] [[add] | [ident]]
.SH "DESCRIçãO"
.PP
O
\fBapt\-cdrom\fR
é usado para adicionar um novo CDROM à lista de fontes disponíveis do APT\&. O
\fBapt\-cdrom\fR
encarrega\-se de determinar a estrutura do disco assim como corrigir várias falhas possíveis e verificar os ficheiros de índice\&.
.PP
É necessário usar o
\fBapt\-cdrom\fR
para adicionar CDs ao sistema APT, não pode ser feito manualmente\&. Mais, cada disco de um conjunto de vários discos tem que ser inserido e sondado separadamente para ter em conta possíveis falhas\&.
.PP
A menos que a opção
\fB\-h\fR, ou
\fB\-\-help\fR
seja fornecida, um dos comandos abaixo têm que estar presentes\&.
.PP
add
.RS 4
add
é usado para adicionar um novo disco à lista de fontes\&. Irá desmontar o dispositivo CDROM, pedir que seja inserido um disco e depois prosseguir com a sua sondagem e cópia dos ficheiros índice\&. Se o disco não possuir um directório
disk
apropriado, ser\-lhe\-à pedido um título descritivo\&.
.sp
O APT usa um ID de CDROM para acompanhar qual disco está actualmente na drive e mantêm uma base de dados desses IDs em
/var/lib/apt/cdroms\&.list
.RE
.PP
ident
.RS 4
Uma ferramenta de depuração para reportar a identificação do disco actual assim como o nome de ficheiro armazenado
.RE
.SH "OPçõES"
.PP
Todas as opções de linha de comandos podem ser definidas usando o ficheiro de configuração, as descrições indicam a opção de configuração a definir\&. Para opções booleanas você pode sobre por o ficheiro de configuração usando algo como
\fB\-f\-\fR,\fB\-\-no\-f\fR,
\fB\-f=no\fR
ou várias outras variantes\&.
.PP
\fB\-d\fR, \fB\-\-cdrom\fR
.RS 4
Ponto de Montagem; especifica a localização para montar o cdrom\&. Este ponto de montagem deve estar listado em
/etc/fstab
e configurado apropriadamente\&. Item de configuração:
Acquire::cdrom::mount\&.
.RE
.PP
\fB\-r\fR, \fB\-\-rename\fR
.RS 4
Renomear um disco; muda a etiqueta de um disco ou sobrepõe a etiqueta fornecida do disco\&. Esta opção irá fazer com que o
\fBapt\-cdrom\fR
pergunte por uma nova etiqueta\&. Item de configuração:
APT::CDROM::Rename\&.
.RE
.PP
\fB\-m\fR, \fB\-\-no\-mount\fR
.RS 4
Nenhuma montagem; impede o
\fBapt\-cdrom\fR
de montar e desmontar o ponto de montagem\&. Item de configuração:
APT::CDROM::NoMount\&.
.RE
.PP
\fB\-f\fR, \fB\-\-fast\fR
.RS 4
Copia rápida; Assume que os ficheiros do pacote são válidos e não verifica cada pacote\&. Este opção só deve ser usada se o
\fBapt\-cdrom\fR
já foi corrido com este disco e não detectou nenhum erro\&. Item de configuração:
APT::CDROM::Fast\&.
.RE
.PP
\fB\-a\fR, \fB\-\-thorough\fR
.RS 4
Sondagem de pacote exaustiva; Esta opção pode ser necessária com alguns discos Debian antigos 1\&.1/1\&.2 que têm ficheiros de pacotes em lugares estranhos\&. Demora muito mais tempo a sondar o CD mas irá apanhá\-los a todos\&.
.RE
.PP
\fB\-n\fR, \fB\-\-just\-print\fR, \fB\-\-recon\fR, \fB\-\-no\-act\fR
.RS 4
Nenhuma alteração; Não altera o ficheiro
\fBsources.list\fR(5)
e não escreve ficheiros índice\&. No entanto, tudo continua a ser verificado\&. Item de configuração:
APT::CDROM::NoAct\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra um sumário curto da utilização\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Mostra a versão do programa\&.
.RE
.PP
\fB\-c\fR, \fB\-\-config\-file\fR
.RS 4
Ficheiro de Configuração; Especifica o ficheiro de configuração a usar\&. O programa irá ler o ficheiro de configuração predefinido e depois este ficheiro de configuração\&. Se as definições de configuração precisarem de ser definidas antes, os ficheiros de configuração predefinidos são analisados especificando um ficheiro com a variável de ambiente
\fBAPT_CONFIG\fR\&. Veja
\fBapt.conf\fR(5)
para informação de sintaxe\&.
.RE
.PP
\fB\-o\fR, \fB\-\-option\fR
.RS 4
Define uma Opção de Configuração; Isto irá definir uma opção de configuração arbitrária\&. A sintaxe é
\fB\-o Foo::Bar=bar\fR\&.
\fB\-o\fR
e
\fB\-\-option\fR
podem ser usadas várias vezes para definir opções diferentes\&.
.RE
.SH "VEJA TAMBéM"
.PP
\fBapt.conf\fR(5),
\fBapt-get\fR(8),
\fBsources.list\fR(5)
.SH "DIAGNóSTICO"
.PP
\fBapt\-cdrom\fR
devolve zero em operação normal, 100 decimal em erro\&.
.SH "BUGS"
.PP
\m[blue]\fBpágina de bugs do APT\fR\m[]\&\s-2\u[1]\d\s+2\&. Se deseja reportar um bug no APT, por favor veja
/usr/share/doc/debian/bug\-reporting\&.txt
ou o comando
\fBreportbug\fR(1)\&.
.SH "TRADUÇÃO"
.PP
A tradução Portuguesa foi feita por Américo Monteiro
<a_monteiro@netcabo\&.pt>
em 2009, 2010\&. A tradução foi revista pela equipa de traduções portuguesas da Debian
<traduz@debianpt\&.org>\&.
.PP
Note que este documento traduzido pode conter partes não traduzidas\&. Isto é feito propositadamente, para evitar perdas de conteúdo quando a tradução está atrasada relativamente ao conteúdo original\&.
.SH "AUTHORS"
.PP
\fBJason Gunthorpe\fR
.RS 4
.RE
.PP
\fBAPT team\fR
.RS 4
.RE
.SH "NOTES"
.IP " 1." 4
página de bugs do APT
.RS 4
\%http://bugs.debian.org/src:apt
.RE
